### ISSUE TITLE
Grafana capacity usage tables not updating

### ISSUE THREAD

**Issue by bwilliam79** [Qumulo/QumuloAlerts#1]
After copying data to a share with a quota, the line chart in Grafana showing quota consumption is updating as expected, but the tables listing the quota limit and current usage are not.

![image](https://github.com/Qumulo/QumuloAlerts/assets/6476126/6e85ebe4-336d-4675-b8b8-7c2e303cd596)

**Comment by bwilliam79** [comment]
This looks like may be related to my AD server becoming unavailable. I noticed after refreshing the Grafana page that no charts at all were updating and it looked like metrics were no longer being received. After powering my AD VM back online, these charts appear to be working again and as expected.

**Comment by bwilliam79** [comment]
These do appear to update after some time, but the tables don't necessarily jive with the line graph. After playing with this a little bit, it may be related to the time frame selected for the Grafana dashboard. I would expect tables to always show the most current value and the trend lines are there to represent historical values.

**Comment by MikeKade** [comment]
Tested, but not found. I set the update time on the Grafana screen to be 1 minute and everything works. If you don't set the update time, then it appears as if nothing is updated...
